### signu user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "sign1u@amil.com",
    "password": "azhera"
}

### Get single user by id
GET http://localhost:3000/auth/12

### Get All user by email
GET http://localhost:3000/auth?email=sign1u@amil.com&password=azhera

### udpate user by id
PATCH http://localhost:3000/auth/111
Content-Type: application/json

{
    "email": "azhera@gmail.com",
    "password": "azherwa3"
}

### Delete user by id
DELETE http://localhost:3000/auth/11

