### signu user

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "aasign1ua@ami1l.com",
    "password": "azheraa"
}

### 
POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email": "aasign1ua@ami1l.com",
    "password": "azheraa"
}

### Get single user by id
GET http://localhost:3000/auth/1

### Get All user by email
GET http://localhost:3000/user?email=sign1u@amil.com

### udpate user by id
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
     "email": "azhera@gmaial.com"
}

### Delete user by id
DELETE http://localhost:3000/auth/11



### get current login user
GET http://localhost:3000/user/current-user


###LOGOUT USER
POST http://localhost:3000/user/logout